clear db;
clear factcount;
clear dbsize;
clear ans;
clear fileID;
clear head;
clear ia;
clear ib;
clear ii;
clear index;
clear pdbtfilename;
clear pred;
clear predsize;
clear reverse_db;
clear tail; 
clear TraceArray;
clear wordsize;

load('alphabetized_words.mat');
load('conceptnet2.mat');
load('h3.mat');
load('params.mat');
load('predicates.mat');
load('sentenceword.mat');
load('svowords.mat');
load('uq_conceptnet.mat');
load('word.mat');